services:
  - type: web
    name: streamlit-app
    env: python
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    autoDeploy: true
